[package]
name = "rust_ffi"
authors = ["CSS Group"]
version = "0.1.0"
edition = "2021"
# build = "build.rs"

[dependencies]
libc = "0.2.9"
c2rust-bitfields = "0.3.0"

[lib]
crate-type = ["rlib"]
name = "rust_ffi"
path = "lib.rs"